# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/control/escalation.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import routeiq.v1.control.escalation_pb2 as routeiq_dot_v1_dot_control_dot_escalation__pb2


class EscalationService(Protocol):
    async def escalate(self, request: routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def resolve_escalation(self, request: routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EscalationServiceASGIApplication(ConnectASGIApplication[EscalationService]):
    def __init__(self, service: EscalationService | AsyncGenerator[EscalationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.control.EscalationService/Escalate": Endpoint.unary(
                    method=MethodInfo(
                        name="Escalate",
                        service_name="routeiq.v1.control.EscalationService",
                        input=routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateRequest,
                        output=routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.escalate,
                ),
                "/routeiq.v1.control.EscalationService/ResolveEscalation": Endpoint.unary(
                    method=MethodInfo(
                        name="ResolveEscalation",
                        service_name="routeiq.v1.control.EscalationService",
                        input=routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationRequest,
                        output=routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.resolve_escalation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.control.EscalationService"


class EscalationServiceClient(ConnectClient):
    async def escalate(
        self,
        request: routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Escalate",
                service_name="routeiq.v1.control.EscalationService",
                input=routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateRequest,
                output=routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def resolve_escalation(
        self,
        request: routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResolveEscalation",
                service_name="routeiq.v1.control.EscalationService",
                input=routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationRequest,
                output=routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class EscalationServiceSync(Protocol):
    def escalate(self, request: routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def resolve_escalation(self, request: routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class EscalationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: EscalationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.control.EscalationService/Escalate": EndpointSync.unary(
                    method=MethodInfo(
                        name="Escalate",
                        service_name="routeiq.v1.control.EscalationService",
                        input=routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateRequest,
                        output=routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.escalate,
                ),
                "/routeiq.v1.control.EscalationService/ResolveEscalation": EndpointSync.unary(
                    method=MethodInfo(
                        name="ResolveEscalation",
                        service_name="routeiq.v1.control.EscalationService",
                        input=routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationRequest,
                        output=routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.resolve_escalation,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.control.EscalationService"


class EscalationServiceClientSync(ConnectClientSync):
    def escalate(
        self,
        request: routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Escalate",
                service_name="routeiq.v1.control.EscalationService",
                input=routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateRequest,
                output=routeiq_dot_v1_dot_control_dot_escalation__pb2.EscalateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def resolve_escalation(
        self,
        request: routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ResolveEscalation",
                service_name="routeiq.v1.control.EscalationService",
                input=routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationRequest,
                output=routeiq_dot_v1_dot_control_dot_escalation__pb2.ResolveEscalationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


