# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/control/escalation.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/control/escalation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#routeiq/v1/control/escalation.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n\x0f\x45scalateRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n\x06reason\x18\x02 \x01(\tR\x06reason\x12\'\n\x0f\x63ontext_summary\x18\x03 \x01(\tR\x0e\x63ontextSummary\x12?\n\x07urgency\x18\x04 \x01(\x0e\x32%.routeiq.v1.control.EscalationUrgencyR\x07urgency\"\xad\x01\n\x10\x45scalateResponse\x12#\n\rescalation_id\x18\x01 \x01(\tR\x0c\x65scalationId\x12\x39\n\x05state\x18\x02 \x01(\x0e\x32#.routeiq.v1.control.EscalationStateR\x05state\x12\x39\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n\x18ResolveEscalationRequest\x12#\n\rescalation_id\x18\x01 \x01(\tR\x0c\x65scalationId\x12\x1e\n\nresolution\x18\x02 \x01(\tR\nresolution\x12\x1a\n\x08\x61pproved\x18\x03 \x01(\x08R\x08\x61pproved\"7\n\x19ResolveEscalationResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted*d\n\x11\x45scalationUrgency\x12\"\n\x1e\x45SCALATION_URGENCY_UNSPECIFIED\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04*l\n\x0f\x45scalationState\x12 \n\x1c\x45SCALATION_STATE_UNSPECIFIED\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\x10\n\x0c\x41\x43KNOWLEDGED\x10\x02\x12\x0c\n\x08RESOLVED\x10\x03\x12\r\n\tTIMED_OUT\x10\x04\x32\xdc\x01\n\x11\x45scalationService\x12U\n\x08\x45scalate\x12#.routeiq.v1.control.EscalateRequest\x1a$.routeiq.v1.control.EscalateResponse\x12p\n\x11ResolveEscalation\x12,.routeiq.v1.control.ResolveEscalationRequest\x1a-.routeiq.v1.control.ResolveEscalationResponseB\x95\x01\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x0f\x45scalationProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.control.escalation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\017EscalationProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1'
  _globals['_ESCALATIONURGENCY']._serialized_start=631
  _globals['_ESCALATIONURGENCY']._serialized_end=731
  _globals['_ESCALATIONSTATE']._serialized_start=733
  _globals['_ESCALATIONSTATE']._serialized_end=841
  _globals['_ESCALATEREQUEST']._serialized_start=93
  _globals['_ESCALATEREQUEST']._serialized_end=271
  _globals['_ESCALATERESPONSE']._serialized_start=274
  _globals['_ESCALATERESPONSE']._serialized_end=447
  _globals['_RESOLVEESCALATIONREQUEST']._serialized_start=449
  _globals['_RESOLVEESCALATIONREQUEST']._serialized_end=572
  _globals['_RESOLVEESCALATIONRESPONSE']._serialized_start=574
  _globals['_RESOLVEESCALATIONRESPONSE']._serialized_end=629
  _globals['_ESCALATIONSERVICE']._serialized_start=844
  _globals['_ESCALATIONSERVICE']._serialized_end=1064
# @@protoc_insertion_point(module_scope)
