# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/control/guardrail.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/control/guardrail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from routeiq.v1.telemetry import entities_pb2 as routeiq_dot_v1_dot_telemetry_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"routeiq/v1/control/guardrail.proto\x12\x12routeiq.v1.control\x1a#routeiq/v1/telemetry/entities.proto\"\xd4\x01\n\x15\x43heckGuardrailRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\'\n\x0fproposed_action\x18\x02 \x01(\tR\x0eproposedAction\x12P\n\x10permission_level\x18\x03 \x01(\x0e\x32%.routeiq.v1.telemetry.PermissionLevelR\x0fpermissionLevel\x12!\n\x0crisk_context\x18\x04 \x01(\tR\x0briskContext\"\xa2\x01\n\x16\x43heckGuardrailResponse\x12>\n\x07verdict\x18\x01 \x01(\x0e\x32$.routeiq.v1.control.GuardrailVerdictR\x07verdict\x12\x16\n\x06reason\x18\x02 \x01(\tR\x06reason\x12\x30\n\x14policy_ids_triggered\x18\x03 \x03(\tR\x12policyIdsTriggered\"\x82\x01\n\x15RegisterPolicyRequest\x12\x1b\n\tpolicy_id\x18\x01 \x01(\tR\x08policyId\x12%\n\x0e\x62undle_version\x18\x02 \x01(\tR\rbundleVersion\x12%\n\x0epolicy_content\x18\x03 \x01(\x0cR\rpolicyContent\"a\n\x16RegisterPolicyResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted\x12+\n\x11\x65\x66\x66\x65\x63tive_version\x18\x02 \x01(\tR\x10\x65\x66\x66\x65\x63tiveVersion*a\n\x10GuardrailVerdict\x12!\n\x1dGUARDRAIL_VERDICT_UNSPECIFIED\x10\x00\x12\t\n\x05\x41LLOW\x10\x01\x12\t\n\x05\x42LOCK\x10\x02\x12\x14\n\x10REQUIRE_APPROVAL\x10\x03\x32\xe4\x01\n\x10GuardrailService\x12g\n\x0e\x43heckGuardrail\x12).routeiq.v1.control.CheckGuardrailRequest\x1a*.routeiq.v1.control.CheckGuardrailResponse\x12g\n\x0eRegisterPolicy\x12).routeiq.v1.control.RegisterPolicyRequest\x1a*.routeiq.v1.control.RegisterPolicyResponseB\x94\x01\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x0eGuardrailProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.control.guardrail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\016GuardrailProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1'
  _globals['_GUARDRAILVERDICT']._serialized_start=707
  _globals['_GUARDRAILVERDICT']._serialized_end=804
  _globals['_CHECKGUARDRAILREQUEST']._serialized_start=96
  _globals['_CHECKGUARDRAILREQUEST']._serialized_end=308
  _globals['_CHECKGUARDRAILRESPONSE']._serialized_start=311
  _globals['_CHECKGUARDRAILRESPONSE']._serialized_end=473
  _globals['_REGISTERPOLICYREQUEST']._serialized_start=476
  _globals['_REGISTERPOLICYREQUEST']._serialized_end=606
  _globals['_REGISTERPOLICYRESPONSE']._serialized_start=608
  _globals['_REGISTERPOLICYRESPONSE']._serialized_end=705
  _globals['_GUARDRAILSERVICE']._serialized_start=807
  _globals['_GUARDRAILSERVICE']._serialized_end=1035
# @@protoc_insertion_point(module_scope)
