# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/control/guardrail.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import routeiq.v1.control.guardrail_pb2 as routeiq_dot_v1_dot_control_dot_guardrail__pb2


class GuardrailService(Protocol):
    async def check_guardrail(self, request: routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def register_policy(self, request: routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class GuardrailServiceASGIApplication(ConnectASGIApplication[GuardrailService]):
    def __init__(self, service: GuardrailService | AsyncGenerator[GuardrailService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.control.GuardrailService/CheckGuardrail": Endpoint.unary(
                    method=MethodInfo(
                        name="CheckGuardrail",
                        service_name="routeiq.v1.control.GuardrailService",
                        input=routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailRequest,
                        output=routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.check_guardrail,
                ),
                "/routeiq.v1.control.GuardrailService/RegisterPolicy": Endpoint.unary(
                    method=MethodInfo(
                        name="RegisterPolicy",
                        service_name="routeiq.v1.control.GuardrailService",
                        input=routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyRequest,
                        output=routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.register_policy,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.control.GuardrailService"


class GuardrailServiceClient(ConnectClient):
    async def check_guardrail(
        self,
        request: routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckGuardrail",
                service_name="routeiq.v1.control.GuardrailService",
                input=routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailRequest,
                output=routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def register_policy(
        self,
        request: routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RegisterPolicy",
                service_name="routeiq.v1.control.GuardrailService",
                input=routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyRequest,
                output=routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class GuardrailServiceSync(Protocol):
    def check_guardrail(self, request: routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def register_policy(self, request: routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class GuardrailServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: GuardrailServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.control.GuardrailService/CheckGuardrail": EndpointSync.unary(
                    method=MethodInfo(
                        name="CheckGuardrail",
                        service_name="routeiq.v1.control.GuardrailService",
                        input=routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailRequest,
                        output=routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.check_guardrail,
                ),
                "/routeiq.v1.control.GuardrailService/RegisterPolicy": EndpointSync.unary(
                    method=MethodInfo(
                        name="RegisterPolicy",
                        service_name="routeiq.v1.control.GuardrailService",
                        input=routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyRequest,
                        output=routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.register_policy,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.control.GuardrailService"


class GuardrailServiceClientSync(ConnectClientSync):
    def check_guardrail(
        self,
        request: routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CheckGuardrail",
                service_name="routeiq.v1.control.GuardrailService",
                input=routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailRequest,
                output=routeiq_dot_v1_dot_control_dot_guardrail__pb2.CheckGuardrailResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def register_policy(
        self,
        request: routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RegisterPolicy",
                service_name="routeiq.v1.control.GuardrailService",
                input=routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyRequest,
                output=routeiq_dot_v1_dot_control_dot_guardrail__pb2.RegisterPolicyResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


