# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/control/intervention.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import routeiq.v1.control.intervention_pb2 as routeiq_dot_v1_dot_control_dot_intervention__pb2


class InterventionService(Protocol):
    async def trigger_intervention(self, request: routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_intervention_status(self, request: routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class InterventionServiceASGIApplication(ConnectASGIApplication[InterventionService]):
    def __init__(self, service: InterventionService | AsyncGenerator[InterventionService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.control.InterventionService/TriggerIntervention": Endpoint.unary(
                    method=MethodInfo(
                        name="TriggerIntervention",
                        service_name="routeiq.v1.control.InterventionService",
                        input=routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionRequest,
                        output=routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.trigger_intervention,
                ),
                "/routeiq.v1.control.InterventionService/GetInterventionStatus": Endpoint.unary(
                    method=MethodInfo(
                        name="GetInterventionStatus",
                        service_name="routeiq.v1.control.InterventionService",
                        input=routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusRequest,
                        output=routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_intervention_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.control.InterventionService"


class InterventionServiceClient(ConnectClient):
    async def trigger_intervention(
        self,
        request: routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TriggerIntervention",
                service_name="routeiq.v1.control.InterventionService",
                input=routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionRequest,
                output=routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_intervention_status(
        self,
        request: routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInterventionStatus",
                service_name="routeiq.v1.control.InterventionService",
                input=routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusRequest,
                output=routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class InterventionServiceSync(Protocol):
    def trigger_intervention(self, request: routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_intervention_status(self, request: routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class InterventionServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: InterventionServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.control.InterventionService/TriggerIntervention": EndpointSync.unary(
                    method=MethodInfo(
                        name="TriggerIntervention",
                        service_name="routeiq.v1.control.InterventionService",
                        input=routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionRequest,
                        output=routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.trigger_intervention,
                ),
                "/routeiq.v1.control.InterventionService/GetInterventionStatus": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetInterventionStatus",
                        service_name="routeiq.v1.control.InterventionService",
                        input=routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusRequest,
                        output=routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_intervention_status,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.control.InterventionService"


class InterventionServiceClientSync(ConnectClientSync):
    def trigger_intervention(
        self,
        request: routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="TriggerIntervention",
                service_name="routeiq.v1.control.InterventionService",
                input=routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionRequest,
                output=routeiq_dot_v1_dot_control_dot_intervention__pb2.TriggerInterventionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_intervention_status(
        self,
        request: routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetInterventionStatus",
                service_name="routeiq.v1.control.InterventionService",
                input=routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusRequest,
                output=routeiq_dot_v1_dot_control_dot_intervention__pb2.GetInterventionStatusResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


