# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/control/intervention.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/control/intervention.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from routeiq.v1.telemetry import entities_pb2 as routeiq_dot_v1_dot_telemetry_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%routeiq/v1/control/intervention.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/telemetry/entities.proto\"\xd4\x01\n\x1aTriggerInterventionRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x38\n\x04kind\x18\x02 \x01(\x0e\x32$.routeiq.v1.control.InterventionKindR\x04kind\x12\x16\n\x06reason\x18\x03 \x01(\tR\x06reason\x12\x45\n\x0c\x64owngrade_to\x18\x04 \x01(\x0e\x32\".routeiq.v1.telemetry.AutonomyModeR\x0b\x64owngradeTo\"\x9b\x01\n\x1bTriggerInterventionResponse\x12\'\n\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12\x18\n\x07\x61pplied\x18\x02 \x01(\x08R\x07\x61pplied\x12\x39\n\napplied_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tappliedAt\"G\n\x1cGetInterventionStatusRequest\x12\'\n\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\"\x9a\x01\n\x1dGetInterventionStatusResponse\x12\'\n\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12\x38\n\x04kind\x18\x02 \x01(\x0e\x32$.routeiq.v1.control.InterventionKindR\x04kind\x12\x16\n\x06\x61\x63tive\x18\x03 \x01(\x08R\x06\x61\x63tive*\x8d\x01\n\x10InterventionKind\x12!\n\x1dINTERVENTION_KIND_UNSPECIFIED\x10\x00\x12\x11\n\rCIRCUIT_BREAK\x10\x01\x12\x0c\n\x08ROLLBACK\x10\x02\x12\x16\n\x12\x41UTONOMY_DOWNGRADE\x10\x03\x12\x0e\n\nMODEL_SWAP\x10\x04\x12\r\n\tHARD_STOP\x10\x05\x32\x8b\x02\n\x13InterventionService\x12v\n\x13TriggerIntervention\x12..routeiq.v1.control.TriggerInterventionRequest\x1a/.routeiq.v1.control.TriggerInterventionResponse\x12|\n\x15GetInterventionStatus\x12\x30.routeiq.v1.control.GetInterventionStatusRequest\x1a\x31.routeiq.v1.control.GetInterventionStatusResponseB\x97\x01\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x11InterventionProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.control.intervention_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\021InterventionProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1'
  _globals['_INTERVENTIONKIND']._serialized_start=735
  _globals['_INTERVENTIONKIND']._serialized_end=876
  _globals['_TRIGGERINTERVENTIONREQUEST']._serialized_start=132
  _globals['_TRIGGERINTERVENTIONREQUEST']._serialized_end=344
  _globals['_TRIGGERINTERVENTIONRESPONSE']._serialized_start=347
  _globals['_TRIGGERINTERVENTIONRESPONSE']._serialized_end=502
  _globals['_GETINTERVENTIONSTATUSREQUEST']._serialized_start=504
  _globals['_GETINTERVENTIONSTATUSREQUEST']._serialized_end=575
  _globals['_GETINTERVENTIONSTATUSRESPONSE']._serialized_start=578
  _globals['_GETINTERVENTIONSTATUSRESPONSE']._serialized_end=732
  _globals['_INTERVENTIONSERVICE']._serialized_start=879
  _globals['_INTERVENTIONSERVICE']._serialized_end=1146
# @@protoc_insertion_point(module_scope)
