# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/control/session.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/control/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from routeiq.v1.telemetry import entities_pb2 as routeiq_dot_v1_dot_telemetry_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n routeiq/v1/control/session.proto\x12\x12routeiq.v1.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/telemetry/entities.proto\"\x8e\x02\n\x13StartSessionRequest\x12\x17\n\x07task_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n\x08\x61gent_id\x18\x02 \x01(\tR\x07\x61gentId\x12\x1b\n\ttenant_id\x18\x03 \x01(\tR\x08tenantId\x12 \n\x0b\x65nvironment\x18\x04 \x01(\tR\x0b\x65nvironment\x12G\n\rautonomy_mode\x18\x05 \x01(\x0e\x32\".routeiq.v1.telemetry.AutonomyModeR\x0c\x61utonomyMode\x12;\n\trisk_tier\x18\x06 \x01(\x0e\x32\x1e.routeiq.v1.telemetry.RiskTierR\x08riskTier\"p\n\x14StartSessionResponse\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x39\n\nstarted_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\"\x87\x01\n\x11\x45ndSessionRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12S\n\x11\x63ompletion_status\x18\x02 \x01(\x0e\x32&.routeiq.v1.telemetry.CompletionStatusR\x10\x63ompletionStatus\"0\n\x12\x45ndSessionResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted\"q\n\x12UpdateStateRequest\x12\x1d\n\nsession_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n\tstate_key\x18\x02 \x01(\tR\x08stateKey\x12\x1f\n\x0bstate_value\x18\x03 \x01(\x0cR\nstateValue\"V\n\x13UpdateStateResponse\x12\x1a\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08R\x08\x61\x63\x63\x65pted\x12#\n\rstate_version\x18\x02 \x01(\tR\x0cstateVersion2\xb0\x02\n\x0eSessionService\x12\x61\n\x0cStartSession\x12\'.routeiq.v1.control.StartSessionRequest\x1a(.routeiq.v1.control.StartSessionResponse\x12[\n\nEndSession\x12%.routeiq.v1.control.EndSessionRequest\x1a&.routeiq.v1.control.EndSessionResponse\x12^\n\x0bUpdateState\x12&.routeiq.v1.control.UpdateStateRequest\x1a\'.routeiq.v1.control.UpdateStateResponseB\x92\x01\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\x0cSessionProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.control.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0build.buf.gen.ssforge.routeiq.routeiq.v1.controlB\014SessionProtoZPbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/control;controlv1'
  _globals['_STARTSESSIONREQUEST']._serialized_start=127
  _globals['_STARTSESSIONREQUEST']._serialized_end=397
  _globals['_STARTSESSIONRESPONSE']._serialized_start=399
  _globals['_STARTSESSIONRESPONSE']._serialized_end=511
  _globals['_ENDSESSIONREQUEST']._serialized_start=514
  _globals['_ENDSESSIONREQUEST']._serialized_end=649
  _globals['_ENDSESSIONRESPONSE']._serialized_start=651
  _globals['_ENDSESSIONRESPONSE']._serialized_end=699
  _globals['_UPDATESTATEREQUEST']._serialized_start=701
  _globals['_UPDATESTATEREQUEST']._serialized_end=814
  _globals['_UPDATESTATERESPONSE']._serialized_start=816
  _globals['_UPDATESTATERESPONSE']._serialized_end=902
  _globals['_SESSIONSERVICE']._serialized_start=905
  _globals['_SESSIONSERVICE']._serialized_end=1209
# @@protoc_insertion_point(module_scope)
