# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/control/session.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import routeiq.v1.control.session_pb2 as routeiq_dot_v1_dot_control_dot_session__pb2


class SessionService(Protocol):
    async def start_session(self, request: routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def end_session(self, request: routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_state(self, request: routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SessionServiceASGIApplication(ConnectASGIApplication[SessionService]):
    def __init__(self, service: SessionService | AsyncGenerator[SessionService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.control.SessionService/StartSession": Endpoint.unary(
                    method=MethodInfo(
                        name="StartSession",
                        service_name="routeiq.v1.control.SessionService",
                        input=routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionRequest,
                        output=routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.start_session,
                ),
                "/routeiq.v1.control.SessionService/EndSession": Endpoint.unary(
                    method=MethodInfo(
                        name="EndSession",
                        service_name="routeiq.v1.control.SessionService",
                        input=routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionRequest,
                        output=routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.end_session,
                ),
                "/routeiq.v1.control.SessionService/UpdateState": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateState",
                        service_name="routeiq.v1.control.SessionService",
                        input=routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateRequest,
                        output=routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_state,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.control.SessionService"


class SessionServiceClient(ConnectClient):
    async def start_session(
        self,
        request: routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartSession",
                service_name="routeiq.v1.control.SessionService",
                input=routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionRequest,
                output=routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def end_session(
        self,
        request: routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="EndSession",
                service_name="routeiq.v1.control.SessionService",
                input=routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionRequest,
                output=routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_state(
        self,
        request: routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateState",
                service_name="routeiq.v1.control.SessionService",
                input=routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateRequest,
                output=routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class SessionServiceSync(Protocol):
    def start_session(self, request: routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def end_session(self, request: routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_state(self, request: routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SessionServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SessionServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.control.SessionService/StartSession": EndpointSync.unary(
                    method=MethodInfo(
                        name="StartSession",
                        service_name="routeiq.v1.control.SessionService",
                        input=routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionRequest,
                        output=routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.start_session,
                ),
                "/routeiq.v1.control.SessionService/EndSession": EndpointSync.unary(
                    method=MethodInfo(
                        name="EndSession",
                        service_name="routeiq.v1.control.SessionService",
                        input=routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionRequest,
                        output=routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.end_session,
                ),
                "/routeiq.v1.control.SessionService/UpdateState": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateState",
                        service_name="routeiq.v1.control.SessionService",
                        input=routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateRequest,
                        output=routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_state,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.control.SessionService"


class SessionServiceClientSync(ConnectClientSync):
    def start_session(
        self,
        request: routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="StartSession",
                service_name="routeiq.v1.control.SessionService",
                input=routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionRequest,
                output=routeiq_dot_v1_dot_control_dot_session__pb2.StartSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def end_session(
        self,
        request: routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="EndSession",
                service_name="routeiq.v1.control.SessionService",
                input=routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionRequest,
                output=routeiq_dot_v1_dot_control_dot_session__pb2.EndSessionResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_state(
        self,
        request: routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateState",
                service_name="routeiq.v1.control.SessionService",
                input=routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateRequest,
                output=routeiq_dot_v1_dot_control_dot_session__pb2.UpdateStateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


