# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/insights/alerts.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/insights/alerts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n routeiq/v1/insights/alerts.proto\x12\x13routeiq.v1.insights\"\xaf\x02\n\tAlertRule\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n\tmetric_id\x18\x02 \x01(\tR\x08metricId\x12<\n\tcondition\x18\x03 \x01(\x0b\x32\x1e.routeiq.v1.insights.ConditionR\tcondition\x12\x39\n\x08severity\x18\x04 \x01(\x0e\x32\x1d.routeiq.v1.insights.SeverityR\x08severity\x12@\n\x07\x61\x63tions\x18\x05 \x03(\x0e\x32&.routeiq.v1.insights.RecommendedActionR\x07\x61\x63tions\x12 \n\x0b\x64\x65scription\x18\x06 \x01(\tR\x0b\x64\x65scription\x12\x18\n\x07\x65nabled\x18\x07 \x01(\x08R\x07\x65nabled\"\x91\x01\n\tCondition\x12-\n\x02op\x18\x01 \x01(\x0e\x32\x1d.routeiq.v1.insights.OperatorR\x02op\x12\x1c\n\tthreshold\x18\x02 \x01(\x01R\tthreshold\x12\x16\n\x06window\x18\x03 \x01(\tR\x06window\x12\x1f\n\x0bmin_samples\x18\x04 \x01(\x05R\nminSamples*l\n\x08Operator\x12\x18\n\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x06\n\x02GT\x10\x01\x12\x06\n\x02LT\x10\x02\x12\x07\n\x03GTE\x10\x03\x12\x07\n\x03LTE\x10\x04\x12\x06\n\x02\x45Q\x10\x05\x12\x0c\n\x08TREND_UP\x10\x06\x12\x0e\n\nTREND_DOWN\x10\x07*S\n\x08Severity\x12\x18\n\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\x0c\n\x08\x43RITICAL\x10\x03\x12\x08\n\x04PAGE\x10\x04*\xa5\x01\n\x11RecommendedAction\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x13\n\x0fREDUCE_AUTONOMY\x10\x01\x12\x11\n\rCIRCUIT_BREAK\x10\x02\x12\x12\n\x0e\x45SCALATE_HUMAN\x10\x03\x12\x14\n\x10ROLLBACK_VERSION\x10\x04\x12\x10\n\x0cSWITCH_MODEL\x10\x05\x12\x14\n\x10REQUIRE_APPROVAL\x10\x06\x42\x94\x01\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x0b\x41lertsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.insights.alerts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\013AlertsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1'
  _globals['_OPERATOR']._serialized_start=511
  _globals['_OPERATOR']._serialized_end=619
  _globals['_SEVERITY']._serialized_start=621
  _globals['_SEVERITY']._serialized_end=704
  _globals['_RECOMMENDEDACTION']._serialized_start=707
  _globals['_RECOMMENDEDACTION']._serialized_end=872
  _globals['_ALERTRULE']._serialized_start=58
  _globals['_ALERTRULE']._serialized_end=361
  _globals['_CONDITION']._serialized_start=364
  _globals['_CONDITION']._serialized_end=509
# @@protoc_insertion_point(module_scope)
