# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/insights/dashboards.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/insights/dashboards.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$routeiq/v1/insights/dashboards.proto\x12\x13routeiq.v1.insights\"\xb0\x01\n\x0f\x44\x61shboardWidget\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n\nmetric_ids\x18\x03 \x03(\tR\tmetricIds\x12\x33\n\x04type\x18\x04 \x01(\x0e\x32\x1f.routeiq.v1.insights.WidgetTypeR\x04type\x12#\n\rdefault_range\x18\x05 \x01(\tR\x0c\x64\x65\x66\x61ultRange\"q\n\tDashboard\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05title\x18\x02 \x01(\tR\x05title\x12>\n\x07widgets\x18\x03 \x03(\x0b\x32$.routeiq.v1.insights.DashboardWidgetR\x07widgets*k\n\nWidgetType\x12\x1b\n\x17WIDGET_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05GAUGE\x10\x01\x12\x0e\n\nTIMESERIES\x10\x02\x12\t\n\x05TABLE\x10\x03\x12\x0b\n\x07HEATMAP\x10\x04\x12\r\n\tSPARKLINE\x10\x05\x42\x98\x01\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x0f\x44\x61shboardsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.insights.dashboards_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\017DashboardsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1'
  _globals['_WIDGETTYPE']._serialized_start=355
  _globals['_WIDGETTYPE']._serialized_end=462
  _globals['_DASHBOARDWIDGET']._serialized_start=62
  _globals['_DASHBOARDWIDGET']._serialized_end=238
  _globals['_DASHBOARD']._serialized_start=240
  _globals['_DASHBOARD']._serialized_end=353
# @@protoc_insertion_point(module_scope)
