# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/insights/interventions.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/insights/interventions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from routeiq.v1.insights import alerts_pb2 as routeiq_dot_v1_dot_insights_dot_alerts__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'routeiq/v1/insights/interventions.proto\x12\x13routeiq.v1.insights\x1a\x1fgoogle/protobuf/timestamp.proto\x1a routeiq/v1/insights/alerts.proto\"\xeb\x02\n\x1aInterventionRecommendation\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\"\n\ralert_rule_id\x18\x02 \x01(\tR\x0b\x61lertRuleId\x12\x1b\n\tmetric_id\x18\x03 \x01(\tR\x08metricId\x12>\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32&.routeiq.v1.insights.RecommendedActionR\x06\x61\x63tion\x12\x1c\n\trationale\x18\x05 \x01(\tR\trationale\x12\x1e\n\nconfidence\x18\x06 \x01(\x01R\nconfidence\x12=\n\x0cgenerated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bgeneratedAt\x12?\n\x06status\x18\x08 \x01(\x0e\x32\'.routeiq.v1.insights.InterventionStatusR\x06status*o\n\x12InterventionStatus\x12#\n\x1fINTERVENTION_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0b\n\x07\x41PPLIED\x10\x02\x12\r\n\tDISMISSED\x10\x03\x12\x0b\n\x07\x45XPIRED\x10\x04\x42\x9b\x01\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x12InterventionsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.insights.interventions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\022InterventionsProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1'
  _globals['_INTERVENTIONSTATUS']._serialized_start=497
  _globals['_INTERVENTIONSTATUS']._serialized_end=608
  _globals['_INTERVENTIONRECOMMENDATION']._serialized_start=132
  _globals['_INTERVENTIONRECOMMENDATION']._serialized_end=495
# @@protoc_insertion_point(module_scope)
