# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/insights/slo.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/insights/slo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1drouteiq/v1/insights/slo.proto\x12\x13routeiq.v1.insights\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x01\n\tSloTarget\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n\tmetric_id\x18\x02 \x01(\tR\x08metricId\x12!\n\x0cworkspace_id\x18\x03 \x01(\tR\x0bworkspaceId\x12\x12\n\x04tier\x18\x04 \x01(\tR\x04tier\x12+\n\x11target_expression\x18\x05 \x01(\tR\x10targetExpression\x12\x16\n\x06window\x18\x06 \x01(\tR\x06window\"\xb1\x02\n\tSloStatus\x12\x15\n\x06slo_id\x18\x01 \x01(\tR\x05sloId\x12\x1b\n\tmetric_id\x18\x02 \x01(\tR\x08metricId\x12#\n\rcurrent_value\x18\x03 \x01(\x01R\x0c\x63urrentValue\x12!\n\x0ctarget_value\x18\x04 \x01(\x01R\x0btargetValue\x12\x33\n\x05state\x18\x05 \x01(\x0e\x32\x1d.routeiq.v1.insights.SloStateR\x05state\x12\x34\n\x16\x65rror_budget_remaining\x18\x06 \x01(\x01R\x14\x65rrorBudgetRemaining\x12=\n\x0c\x65valuated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0b\x65valuatedAt*M\n\x08SloState\x12\x19\n\x15SLO_STATE_UNSPECIFIED\x10\x00\x12\x0b\n\x07MEETING\x10\x01\x12\x0b\n\x07\x41T_RISK\x10\x02\x12\x0c\n\x08\x42REACHED\x10\x03\x42\x91\x01\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\x08SloProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.insights.slo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n1build.buf.gen.ssforge.routeiq.routeiq.v1.insightsB\010SloProtoZRbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/insights;insightsv1'
  _globals['_SLOSTATE']._serialized_start=578
  _globals['_SLOSTATE']._serialized_end=655
  _globals['_SLOTARGET']._serialized_start=88
  _globals['_SLOTARGET']._serialized_end=268
  _globals['_SLOSTATUS']._serialized_start=271
  _globals['_SLOSTATUS']._serialized_end=576
# @@protoc_insertion_point(module_scope)
