# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/admin/billing.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/admin/billing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from routeiq.v1.admin import organization_pb2 as routeiq_dot_v1_dot_admin_dot_organization__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1erouteiq/v1/admin/billing.proto\x12\x10routeiq.v1.admin\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#routeiq/v1/admin/organization.proto\"\xdf\x02\n\x0cUsageSummary\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12=\n\x0cperiod_start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bperiodStart\x12\x39\n\nperiod_end\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tperiodEnd\x12\'\n\x0f\x65vents_ingested\x18\x04 \x01(\x03R\x0e\x65ventsIngested\x12+\n\x11metrics_evaluated\x18\x05 \x01(\x03R\x10metricsEvaluated\x12\x30\n\x14\x66rontier_judge_calls\x18\x06 \x01(\x03R\x12\x66rontierJudgeCalls\x12$\n\x0etotal_cost_usd\x18\x07 \x01(\x01R\x0ctotalCostUsd\"\xe6\x01\n\x05Quota\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12*\n\x04tier\x18\x02 \x01(\x0e\x32\x16.routeiq.v1.admin.TierR\x04tier\x12(\n\x10\x65vents_per_month\x18\x03 \x01(\x03R\x0e\x65ventsPerMonth\x12\x37\n\x18\x66rontier_calls_per_month\x18\x04 \x01(\x03R\x15\x66rontierCallsPerMonth\x12%\n\x0eretention_days\x18\x05 \x01(\x03R\rretentionDays\"\xb4\x01\n\x0fGetUsageRequest\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12=\n\x0cperiod_start\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0bperiodStart\x12\x39\n\nperiod_end\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tperiodEnd\":\n\x0fGetQuotaRequest\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId2\xa7\x01\n\x0e\x42illingService\x12M\n\x08GetUsage\x12!.routeiq.v1.admin.GetUsageRequest\x1a\x1e.routeiq.v1.admin.UsageSummary\x12\x46\n\x08GetQuota\x12!.routeiq.v1.admin.GetQuotaRequest\x1a\x17.routeiq.v1.admin.QuotaB\x8c\x01\n.build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\x0c\x42illingProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.admin.billing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\014BillingProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1'
  _globals['_USAGESUMMARY']._serialized_start=123
  _globals['_USAGESUMMARY']._serialized_end=474
  _globals['_QUOTA']._serialized_start=477
  _globals['_QUOTA']._serialized_end=707
  _globals['_GETUSAGEREQUEST']._serialized_start=710
  _globals['_GETUSAGEREQUEST']._serialized_end=890
  _globals['_GETQUOTAREQUEST']._serialized_start=892
  _globals['_GETQUOTAREQUEST']._serialized_end=950
  _globals['_BILLINGSERVICE']._serialized_start=953
  _globals['_BILLINGSERVICE']._serialized_end=1120
# @@protoc_insertion_point(module_scope)
