# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/admin/billing.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import routeiq.v1.admin.billing_pb2 as routeiq_dot_v1_dot_admin_dot_billing__pb2


class BillingService(Protocol):
    async def get_usage(self, request: routeiq_dot_v1_dot_admin_dot_billing__pb2.GetUsageRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_billing__pb2.UsageSummary:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_quota(self, request: routeiq_dot_v1_dot_admin_dot_billing__pb2.GetQuotaRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_billing__pb2.Quota:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class BillingServiceASGIApplication(ConnectASGIApplication[BillingService]):
    def __init__(self, service: BillingService | AsyncGenerator[BillingService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.admin.BillingService/GetUsage": Endpoint.unary(
                    method=MethodInfo(
                        name="GetUsage",
                        service_name="routeiq.v1.admin.BillingService",
                        input=routeiq_dot_v1_dot_admin_dot_billing__pb2.GetUsageRequest,
                        output=routeiq_dot_v1_dot_admin_dot_billing__pb2.UsageSummary,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_usage,
                ),
                "/routeiq.v1.admin.BillingService/GetQuota": Endpoint.unary(
                    method=MethodInfo(
                        name="GetQuota",
                        service_name="routeiq.v1.admin.BillingService",
                        input=routeiq_dot_v1_dot_admin_dot_billing__pb2.GetQuotaRequest,
                        output=routeiq_dot_v1_dot_admin_dot_billing__pb2.Quota,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_quota,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.BillingService"


class BillingServiceClient(ConnectClient):
    async def get_usage(
        self,
        request: routeiq_dot_v1_dot_admin_dot_billing__pb2.GetUsageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_billing__pb2.UsageSummary:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUsage",
                service_name="routeiq.v1.admin.BillingService",
                input=routeiq_dot_v1_dot_admin_dot_billing__pb2.GetUsageRequest,
                output=routeiq_dot_v1_dot_admin_dot_billing__pb2.UsageSummary,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_quota(
        self,
        request: routeiq_dot_v1_dot_admin_dot_billing__pb2.GetQuotaRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_billing__pb2.Quota:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetQuota",
                service_name="routeiq.v1.admin.BillingService",
                input=routeiq_dot_v1_dot_admin_dot_billing__pb2.GetQuotaRequest,
                output=routeiq_dot_v1_dot_admin_dot_billing__pb2.Quota,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class BillingServiceSync(Protocol):
    def get_usage(self, request: routeiq_dot_v1_dot_admin_dot_billing__pb2.GetUsageRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_billing__pb2.UsageSummary:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_quota(self, request: routeiq_dot_v1_dot_admin_dot_billing__pb2.GetQuotaRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_billing__pb2.Quota:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class BillingServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: BillingServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.admin.BillingService/GetUsage": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetUsage",
                        service_name="routeiq.v1.admin.BillingService",
                        input=routeiq_dot_v1_dot_admin_dot_billing__pb2.GetUsageRequest,
                        output=routeiq_dot_v1_dot_admin_dot_billing__pb2.UsageSummary,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_usage,
                ),
                "/routeiq.v1.admin.BillingService/GetQuota": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetQuota",
                        service_name="routeiq.v1.admin.BillingService",
                        input=routeiq_dot_v1_dot_admin_dot_billing__pb2.GetQuotaRequest,
                        output=routeiq_dot_v1_dot_admin_dot_billing__pb2.Quota,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_quota,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.BillingService"


class BillingServiceClientSync(ConnectClientSync):
    def get_usage(
        self,
        request: routeiq_dot_v1_dot_admin_dot_billing__pb2.GetUsageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_billing__pb2.UsageSummary:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUsage",
                service_name="routeiq.v1.admin.BillingService",
                input=routeiq_dot_v1_dot_admin_dot_billing__pb2.GetUsageRequest,
                output=routeiq_dot_v1_dot_admin_dot_billing__pb2.UsageSummary,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_quota(
        self,
        request: routeiq_dot_v1_dot_admin_dot_billing__pb2.GetQuotaRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_billing__pb2.Quota:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetQuota",
                service_name="routeiq.v1.admin.BillingService",
                input=routeiq_dot_v1_dot_admin_dot_billing__pb2.GetQuotaRequest,
                output=routeiq_dot_v1_dot_admin_dot_billing__pb2.Quota,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


