# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/admin/identity.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import routeiq.v1.admin.identity_pb2 as routeiq_dot_v1_dot_admin_dot_identity__pb2


class IdentityService(Protocol):
    async def invite_user(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.InviteUserRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.User:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_user(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.GetUserRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.User:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def assign_role(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.AssignRoleRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.RoleAssignment:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_api_key(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.CreateApiKeyRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.ApiKey:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def revoke_api_key(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.RevokeApiKeyRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_api_keys(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class IdentityServiceASGIApplication(ConnectASGIApplication[IdentityService]):
    def __init__(self, service: IdentityService | AsyncGenerator[IdentityService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.admin.IdentityService/InviteUser": Endpoint.unary(
                    method=MethodInfo(
                        name="InviteUser",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.InviteUserRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.User,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.invite_user,
                ),
                "/routeiq.v1.admin.IdentityService/GetUser": Endpoint.unary(
                    method=MethodInfo(
                        name="GetUser",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.GetUserRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.User,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_user,
                ),
                "/routeiq.v1.admin.IdentityService/AssignRole": Endpoint.unary(
                    method=MethodInfo(
                        name="AssignRole",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.AssignRoleRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.RoleAssignment,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.assign_role,
                ),
                "/routeiq.v1.admin.IdentityService/CreateApiKey": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateApiKey",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.CreateApiKeyRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.ApiKey,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_api_key,
                ),
                "/routeiq.v1.admin.IdentityService/RevokeApiKey": Endpoint.unary(
                    method=MethodInfo(
                        name="RevokeApiKey",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.RevokeApiKeyRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.revoke_api_key,
                ),
                "/routeiq.v1.admin.IdentityService/ListApiKeys": Endpoint.unary(
                    method=MethodInfo(
                        name="ListApiKeys",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_api_keys,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.IdentityService"


class IdentityServiceClient(ConnectClient):
    async def invite_user(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.InviteUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.User:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="InviteUser",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.InviteUserRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.User,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_user(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.GetUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.User:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.GetUserRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.User,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def assign_role(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.AssignRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.RoleAssignment:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AssignRole",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.AssignRoleRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.RoleAssignment,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_api_key(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.CreateApiKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.ApiKey:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateApiKey",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.CreateApiKeyRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.ApiKey,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def revoke_api_key(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.RevokeApiKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeApiKey",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.RevokeApiKeyRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_api_keys(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListApiKeys",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class IdentityServiceSync(Protocol):
    def invite_user(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.InviteUserRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.User:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_user(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.GetUserRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.User:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def assign_role(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.AssignRoleRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.RoleAssignment:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_api_key(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.CreateApiKeyRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.ApiKey:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def revoke_api_key(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.RevokeApiKeyRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_api_keys(self, request: routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class IdentityServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: IdentityServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.admin.IdentityService/InviteUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="InviteUser",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.InviteUserRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.User,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.invite_user,
                ),
                "/routeiq.v1.admin.IdentityService/GetUser": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetUser",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.GetUserRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.User,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_user,
                ),
                "/routeiq.v1.admin.IdentityService/AssignRole": EndpointSync.unary(
                    method=MethodInfo(
                        name="AssignRole",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.AssignRoleRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.RoleAssignment,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.assign_role,
                ),
                "/routeiq.v1.admin.IdentityService/CreateApiKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateApiKey",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.CreateApiKeyRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.ApiKey,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_api_key,
                ),
                "/routeiq.v1.admin.IdentityService/RevokeApiKey": EndpointSync.unary(
                    method=MethodInfo(
                        name="RevokeApiKey",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.RevokeApiKeyRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.revoke_api_key,
                ),
                "/routeiq.v1.admin.IdentityService/ListApiKeys": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListApiKeys",
                        service_name="routeiq.v1.admin.IdentityService",
                        input=routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysRequest,
                        output=routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_api_keys,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.IdentityService"


class IdentityServiceClientSync(ConnectClientSync):
    def invite_user(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.InviteUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.User:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="InviteUser",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.InviteUserRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.User,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_user(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.GetUserRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.User:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUser",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.GetUserRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.User,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def assign_role(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.AssignRoleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.RoleAssignment:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="AssignRole",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.AssignRoleRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.RoleAssignment,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_api_key(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.CreateApiKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.ApiKey:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateApiKey",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.CreateApiKeyRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.ApiKey,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def revoke_api_key(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.RevokeApiKeyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="RevokeApiKey",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.RevokeApiKeyRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_api_keys(
        self,
        request: routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListApiKeys",
                service_name="routeiq.v1.admin.IdentityService",
                input=routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysRequest,
                output=routeiq_dot_v1_dot_admin_dot_identity__pb2.ListApiKeysResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


