# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/admin/organization.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import routeiq.v1.admin.organization_pb2 as routeiq_dot_v1_dot_admin_dot_organization__pb2


class OrganizationService(Protocol):
    async def create_organization(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateOrganizationRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_organization(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.GetOrganizationRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_organizations(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_organization(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateOrganizationRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_organization(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.DeleteOrganizationRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def create_workspace(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateWorkspaceRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_workspaces(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def update_workspace(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateWorkspaceRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class OrganizationServiceASGIApplication(ConnectASGIApplication[OrganizationService]):
    def __init__(self, service: OrganizationService | AsyncGenerator[OrganizationService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.admin.OrganizationService/CreateOrganization": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateOrganization",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateOrganizationRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_organization,
                ),
                "/routeiq.v1.admin.OrganizationService/GetOrganization": Endpoint.unary(
                    method=MethodInfo(
                        name="GetOrganization",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.GetOrganizationRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_organization,
                ),
                "/routeiq.v1.admin.OrganizationService/ListOrganizations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListOrganizations",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_organizations,
                ),
                "/routeiq.v1.admin.OrganizationService/UpdateOrganization": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateOrganization",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateOrganizationRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_organization,
                ),
                "/routeiq.v1.admin.OrganizationService/DeleteOrganization": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteOrganization",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.DeleteOrganizationRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_organization,
                ),
                "/routeiq.v1.admin.OrganizationService/CreateWorkspace": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateWorkspace",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateWorkspaceRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_workspace,
                ),
                "/routeiq.v1.admin.OrganizationService/ListWorkspaces": Endpoint.unary(
                    method=MethodInfo(
                        name="ListWorkspaces",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_workspaces,
                ),
                "/routeiq.v1.admin.OrganizationService/UpdateWorkspace": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateWorkspace",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateWorkspaceRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.update_workspace,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.OrganizationService"


class OrganizationServiceClient(ConnectClient):
    async def create_organization(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateOrganizationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateOrganization",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateOrganizationRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_organization(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.GetOrganizationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetOrganization",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.GetOrganizationRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_organizations(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListOrganizations",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_organization(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateOrganizationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateOrganization",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateOrganizationRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_organization(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.DeleteOrganizationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteOrganization",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.DeleteOrganizationRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def create_workspace(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateWorkspaceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateWorkspace",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateWorkspaceRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_workspaces(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWorkspaces",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update_workspace(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateWorkspaceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateWorkspace",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateWorkspaceRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class OrganizationServiceSync(Protocol):
    def create_organization(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateOrganizationRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_organization(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.GetOrganizationRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_organizations(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_organization(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateOrganizationRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_organization(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.DeleteOrganizationRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def create_workspace(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateWorkspaceRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_workspaces(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def update_workspace(self, request: routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateWorkspaceRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class OrganizationServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: OrganizationServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.admin.OrganizationService/CreateOrganization": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateOrganization",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateOrganizationRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_organization,
                ),
                "/routeiq.v1.admin.OrganizationService/GetOrganization": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetOrganization",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.GetOrganizationRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_organization,
                ),
                "/routeiq.v1.admin.OrganizationService/ListOrganizations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListOrganizations",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_organizations,
                ),
                "/routeiq.v1.admin.OrganizationService/UpdateOrganization": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateOrganization",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateOrganizationRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_organization,
                ),
                "/routeiq.v1.admin.OrganizationService/DeleteOrganization": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteOrganization",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.DeleteOrganizationRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_organization,
                ),
                "/routeiq.v1.admin.OrganizationService/CreateWorkspace": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateWorkspace",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateWorkspaceRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_workspace,
                ),
                "/routeiq.v1.admin.OrganizationService/ListWorkspaces": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListWorkspaces",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_workspaces,
                ),
                "/routeiq.v1.admin.OrganizationService/UpdateWorkspace": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateWorkspace",
                        service_name="routeiq.v1.admin.OrganizationService",
                        input=routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateWorkspaceRequest,
                        output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update_workspace,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.OrganizationService"


class OrganizationServiceClientSync(ConnectClientSync):
    def create_organization(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateOrganizationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateOrganization",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateOrganizationRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_organization(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.GetOrganizationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetOrganization",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.GetOrganizationRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_organizations(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListOrganizations",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListOrganizationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_organization(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateOrganizationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateOrganization",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateOrganizationRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Organization,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_organization(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.DeleteOrganizationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteOrganization",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.DeleteOrganizationRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def create_workspace(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateWorkspaceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateWorkspace",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.CreateWorkspaceRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_workspaces(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListWorkspaces",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.ListWorkspacesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update_workspace(
        self,
        request: routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateWorkspaceRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateWorkspace",
                service_name="routeiq.v1.admin.OrganizationService",
                input=routeiq_dot_v1_dot_admin_dot_organization__pb2.UpdateWorkspaceRequest,
                output=routeiq_dot_v1_dot_admin_dot_organization__pb2.Workspace,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


