# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/admin/policy.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import routeiq.v1.admin.policy_pb2 as routeiq_dot_v1_dot_admin_dot_policy__pb2


class PolicyService(Protocol):
    async def create_policy_bundle(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.CreatePolicyBundleRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_policy_bundle(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.GetPolicyBundleRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_policy_bundles(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def activate_policy_bundle(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.ActivatePolicyBundleRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_policy_bundle(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.DeletePolicyBundleRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PolicyServiceASGIApplication(ConnectASGIApplication[PolicyService]):
    def __init__(self, service: PolicyService | AsyncGenerator[PolicyService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.admin.PolicyService/CreatePolicyBundle": Endpoint.unary(
                    method=MethodInfo(
                        name="CreatePolicyBundle",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.CreatePolicyBundleRequest,
                        output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_policy_bundle,
                ),
                "/routeiq.v1.admin.PolicyService/GetPolicyBundle": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPolicyBundle",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.GetPolicyBundleRequest,
                        output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_policy_bundle,
                ),
                "/routeiq.v1.admin.PolicyService/ListPolicyBundles": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPolicyBundles",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesRequest,
                        output=routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_policy_bundles,
                ),
                "/routeiq.v1.admin.PolicyService/ActivatePolicyBundle": Endpoint.unary(
                    method=MethodInfo(
                        name="ActivatePolicyBundle",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.ActivatePolicyBundleRequest,
                        output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.activate_policy_bundle,
                ),
                "/routeiq.v1.admin.PolicyService/DeletePolicyBundle": Endpoint.unary(
                    method=MethodInfo(
                        name="DeletePolicyBundle",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.DeletePolicyBundleRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_policy_bundle,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.PolicyService"


class PolicyServiceClient(ConnectClient):
    async def create_policy_bundle(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.CreatePolicyBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePolicyBundle",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.CreatePolicyBundleRequest,
                output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_policy_bundle(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.GetPolicyBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPolicyBundle",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.GetPolicyBundleRequest,
                output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_policy_bundles(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPolicyBundles",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesRequest,
                output=routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def activate_policy_bundle(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.ActivatePolicyBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ActivatePolicyBundle",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.ActivatePolicyBundleRequest,
                output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_policy_bundle(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.DeletePolicyBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeletePolicyBundle",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.DeletePolicyBundleRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class PolicyServiceSync(Protocol):
    def create_policy_bundle(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.CreatePolicyBundleRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_policy_bundle(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.GetPolicyBundleRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_policy_bundles(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def activate_policy_bundle(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.ActivatePolicyBundleRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_policy_bundle(self, request: routeiq_dot_v1_dot_admin_dot_policy__pb2.DeletePolicyBundleRequest, ctx: RequestContext) -> google_dot_protobuf_dot_empty__pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class PolicyServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: PolicyServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.admin.PolicyService/CreatePolicyBundle": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreatePolicyBundle",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.CreatePolicyBundleRequest,
                        output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_policy_bundle,
                ),
                "/routeiq.v1.admin.PolicyService/GetPolicyBundle": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPolicyBundle",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.GetPolicyBundleRequest,
                        output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_policy_bundle,
                ),
                "/routeiq.v1.admin.PolicyService/ListPolicyBundles": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPolicyBundles",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesRequest,
                        output=routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_policy_bundles,
                ),
                "/routeiq.v1.admin.PolicyService/ActivatePolicyBundle": EndpointSync.unary(
                    method=MethodInfo(
                        name="ActivatePolicyBundle",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.ActivatePolicyBundleRequest,
                        output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.activate_policy_bundle,
                ),
                "/routeiq.v1.admin.PolicyService/DeletePolicyBundle": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeletePolicyBundle",
                        service_name="routeiq.v1.admin.PolicyService",
                        input=routeiq_dot_v1_dot_admin_dot_policy__pb2.DeletePolicyBundleRequest,
                        output=google_dot_protobuf_dot_empty__pb2.Empty,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_policy_bundle,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.PolicyService"


class PolicyServiceClientSync(ConnectClientSync):
    def create_policy_bundle(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.CreatePolicyBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreatePolicyBundle",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.CreatePolicyBundleRequest,
                output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_policy_bundle(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.GetPolicyBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPolicyBundle",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.GetPolicyBundleRequest,
                output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_policy_bundles(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPolicyBundles",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesRequest,
                output=routeiq_dot_v1_dot_admin_dot_policy__pb2.ListPolicyBundlesResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def activate_policy_bundle(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.ActivatePolicyBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ActivatePolicyBundle",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.ActivatePolicyBundleRequest,
                output=routeiq_dot_v1_dot_admin_dot_policy__pb2.PolicyBundle,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_policy_bundle(
        self,
        request: routeiq_dot_v1_dot_admin_dot_policy__pb2.DeletePolicyBundleRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> google_dot_protobuf_dot_empty__pb2.Empty:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeletePolicyBundle",
                service_name="routeiq.v1.admin.PolicyService",
                input=routeiq_dot_v1_dot_admin_dot_policy__pb2.DeletePolicyBundleRequest,
                output=google_dot_protobuf_dot_empty__pb2.Empty,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


