# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: routeiq/v1/admin/slo_config.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import routeiq.v1.admin.slo_config_pb2 as routeiq_dot_v1_dot_admin_dot_slo__config__pb2


class SloConfigService(Protocol):
    async def get_slo_overrides(self, request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.GetSloOverridesRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def set_slo_override(self, request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SetSloOverrideRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverride:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def delete_slo_override(self, request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.DeleteSloOverrideRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SloConfigServiceASGIApplication(ConnectASGIApplication[SloConfigService]):
    def __init__(self, service: SloConfigService | AsyncGenerator[SloConfigService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/routeiq.v1.admin.SloConfigService/GetSloOverrides": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSloOverrides",
                        service_name="routeiq.v1.admin.SloConfigService",
                        input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.GetSloOverridesRequest,
                        output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_slo_overrides,
                ),
                "/routeiq.v1.admin.SloConfigService/SetSloOverride": Endpoint.unary(
                    method=MethodInfo(
                        name="SetSloOverride",
                        service_name="routeiq.v1.admin.SloConfigService",
                        input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SetSloOverrideRequest,
                        output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverride,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.set_slo_override,
                ),
                "/routeiq.v1.admin.SloConfigService/DeleteSloOverride": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteSloOverride",
                        service_name="routeiq.v1.admin.SloConfigService",
                        input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.DeleteSloOverrideRequest,
                        output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.delete_slo_override,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.SloConfigService"


class SloConfigServiceClient(ConnectClient):
    async def get_slo_overrides(
        self,
        request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.GetSloOverridesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSloOverrides",
                service_name="routeiq.v1.admin.SloConfigService",
                input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.GetSloOverridesRequest,
                output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def set_slo_override(
        self,
        request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SetSloOverrideRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverride:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetSloOverride",
                service_name="routeiq.v1.admin.SloConfigService",
                input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SetSloOverrideRequest,
                output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverride,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_slo_override(
        self,
        request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.DeleteSloOverrideRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSloOverride",
                service_name="routeiq.v1.admin.SloConfigService",
                input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.DeleteSloOverrideRequest,
                output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class SloConfigServiceSync(Protocol):
    def get_slo_overrides(self, request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.GetSloOverridesRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def set_slo_override(self, request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SetSloOverrideRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverride:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def delete_slo_override(self, request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.DeleteSloOverrideRequest, ctx: RequestContext) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class SloConfigServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: SloConfigServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/routeiq.v1.admin.SloConfigService/GetSloOverrides": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSloOverrides",
                        service_name="routeiq.v1.admin.SloConfigService",
                        input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.GetSloOverridesRequest,
                        output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_slo_overrides,
                ),
                "/routeiq.v1.admin.SloConfigService/SetSloOverride": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetSloOverride",
                        service_name="routeiq.v1.admin.SloConfigService",
                        input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SetSloOverrideRequest,
                        output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverride,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.set_slo_override,
                ),
                "/routeiq.v1.admin.SloConfigService/DeleteSloOverride": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteSloOverride",
                        service_name="routeiq.v1.admin.SloConfigService",
                        input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.DeleteSloOverrideRequest,
                        output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete_slo_override,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/routeiq.v1.admin.SloConfigService"


class SloConfigServiceClientSync(ConnectClientSync):
    def get_slo_overrides(
        self,
        request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.GetSloOverridesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSloOverrides",
                service_name="routeiq.v1.admin.SloConfigService",
                input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.GetSloOverridesRequest,
                output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def set_slo_override(
        self,
        request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SetSloOverrideRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverride:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetSloOverride",
                service_name="routeiq.v1.admin.SloConfigService",
                input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SetSloOverrideRequest,
                output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverride,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete_slo_override(
        self,
        request: routeiq_dot_v1_dot_admin_dot_slo__config__pb2.DeleteSloOverrideRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteSloOverride",
                service_name="routeiq.v1.admin.SloConfigService",
                input=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.DeleteSloOverrideRequest,
                output=routeiq_dot_v1_dot_admin_dot_slo__config__pb2.SloOverrides,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


