# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/admin/slo_config.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/admin/slo_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!routeiq/v1/admin/slo_config.proto\x12\x10routeiq.v1.admin\"\x8e\x01\n\x0bSloOverride\x12\x1b\n\tmetric_id\x18\x01 \x01(\tR\x08metricId\x12!\n\x0cworkspace_id\x18\x02 \x01(\tR\x0bworkspaceId\x12\x12\n\x04tier\x18\x03 \x01(\tR\x04tier\x12+\n\x11target_expression\x18\x04 \x01(\tR\x10targetExpression\"n\n\x0cSloOverrides\x12!\n\x0cworkspace_id\x18\x01 \x01(\tR\x0bworkspaceId\x12;\n\toverrides\x18\x02 \x03(\x0b\x32\x1d.routeiq.v1.admin.SloOverrideR\toverrides\";\n\x16GetSloOverridesRequest\x12!\n\x0cworkspace_id\x18\x01 \x01(\tR\x0bworkspaceId\"R\n\x15SetSloOverrideRequest\x12\x39\n\x08override\x18\x01 \x01(\x0b\x32\x1d.routeiq.v1.admin.SloOverrideR\x08override\"n\n\x18\x44\x65leteSloOverrideRequest\x12\x1b\n\tmetric_id\x18\x01 \x01(\tR\x08metricId\x12!\n\x0cworkspace_id\x18\x02 \x01(\tR\x0bworkspaceId\x12\x12\n\x04tier\x18\x03 \x01(\tR\x04tier2\xaa\x02\n\x10SloConfigService\x12[\n\x0fGetSloOverrides\x12(.routeiq.v1.admin.GetSloOverridesRequest\x1a\x1e.routeiq.v1.admin.SloOverrides\x12X\n\x0eSetSloOverride\x12\'.routeiq.v1.admin.SetSloOverrideRequest\x1a\x1d.routeiq.v1.admin.SloOverride\x12_\n\x11\x44\x65leteSloOverride\x12*.routeiq.v1.admin.DeleteSloOverrideRequest\x1a\x1e.routeiq.v1.admin.SloOverridesB\x8e\x01\n.build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\x0eSloConfigProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.admin.slo_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.build.buf.gen.ssforge.routeiq.routeiq.v1.adminB\016SloConfigProtoZLbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/admin;adminv1'
  _globals['_SLOOVERRIDE']._serialized_start=56
  _globals['_SLOOVERRIDE']._serialized_end=198
  _globals['_SLOOVERRIDES']._serialized_start=200
  _globals['_SLOOVERRIDES']._serialized_end=310
  _globals['_GETSLOOVERRIDESREQUEST']._serialized_start=312
  _globals['_GETSLOOVERRIDESREQUEST']._serialized_end=371
  _globals['_SETSLOOVERRIDEREQUEST']._serialized_start=373
  _globals['_SETSLOOVERRIDEREQUEST']._serialized_end=455
  _globals['_DELETESLOOVERRIDEREQUEST']._serialized_start=457
  _globals['_DELETESLOOVERRIDEREQUEST']._serialized_end=567
  _globals['_SLOCONFIGSERVICE']._serialized_start=570
  _globals['_SLOCONFIGSERVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
