# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/telemetry/conventions.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/telemetry/conventions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from routeiq.v1.telemetry import entities_pb2 as routeiq_dot_v1_dot_telemetry_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&routeiq/v1/telemetry/conventions.proto\x12\x14routeiq.v1.telemetry\x1a#routeiq/v1/telemetry/entities.proto\"\xc1\x01\n\x12SemanticConvention\x12(\n\x10proto_field_path\x18\x01 \x01(\tR\x0eprotoFieldPath\x12,\n\x12otel_attribute_key\x18\x02 \x01(\tR\x10otelAttributeKey\x12\x37\n\x04type\x18\x03 \x01(\x0e\x32#.routeiq.v1.telemetry.AttributeTypeR\x04type\x12\x1a\n\x08required\x18\x04 \x01(\x08R\x08required\"`\n\x12\x43onventionRegistry\x12J\n\x0b\x63onventions\x18\x01 \x03(\x0b\x32(.routeiq.v1.telemetry.SemanticConventionR\x0b\x63onventionsB\x9c\x01\n2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\x10\x43onventionsProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.telemetry.conventions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\020ConventionsProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1'
  _globals['_SEMANTICCONVENTION']._serialized_start=102
  _globals['_SEMANTICCONVENTION']._serialized_end=295
  _globals['_CONVENTIONREGISTRY']._serialized_start=297
  _globals['_CONVENTIONREGISTRY']._serialized_end=393
# @@protoc_insertion_point(module_scope)
