# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: routeiq/v1/telemetry/entities.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'routeiq/v1/telemetry/entities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#routeiq/v1/telemetry/entities.proto\x12\x14routeiq.v1.telemetry*x\n\x10\x43ompletionStatus\x12!\n\x1d\x43OMPLETION_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x0b\n\x07PARTIAL\x10\x03\x12\r\n\tCANCELLED\x10\x04\x12\x0b\n\x07TIMEOUT\x10\x05*\xd2\x01\n\x0f\x46\x61ilureCategory\x12 \n\x1c\x46\x41ILURE_CATEGORY_UNSPECIFIED\x10\x00\x12\x0e\n\nTOOL_ERROR\x10\x01\x12\x0f\n\x0bMODEL_ERROR\x10\x02\x12\x10\n\x0cPOLICY_BLOCK\x10\x03\x12\x11\n\rLOOP_DETECTED\x10\x04\x12\x14\n\x10TIMEOUT_EXCEEDED\x10\x05\x12\x13\n\x0fHUMAN_CANCELLED\x10\x06\x12\x16\n\x12RESOURCE_EXHAUSTED\x10\x07\x12\x14\n\x10\x43ONTEXT_OVERFLOW\x10\x08*b\n\x0c\x41utonomyMode\x12\x1d\n\x19\x41UTONOMY_MODE_UNSPECIFIED\x10\x00\x12\x0e\n\nSUPERVISED\x10\x01\x12\x13\n\x0fSEMI_AUTONOMOUS\x10\x02\x12\x0e\n\nAUTONOMOUS\x10\x03*R\n\x08RiskTier\x12\x19\n\x15RISK_TIER_UNSPECIFIED\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\n\n\x06MEDIUM\x10\x02\x12\x08\n\x04HIGH\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04*n\n\x0fPermissionLevel\x12 \n\x1cPERMISSION_LEVEL_UNSPECIFIED\x10\x00\x12\r\n\tREAD_ONLY\x10\x01\x12\x0e\n\nREAD_WRITE\x10\x02\x12\x0e\n\nPRIVILEGED\x10\x03\x12\n\n\x06SYSTEM\x10\x04*\x88\x01\n\x10ToolResultStatus\x12\"\n\x1eTOOL_RESULT_STATUS_UNSPECIFIED\x10\x00\x12\x10\n\x0cTOOL_SUCCESS\x10\x01\x12\x10\n\x0cTOOL_FAILURE\x10\x02\x12\x10\n\x0cTOOL_TIMEOUT\x10\x03\x12\x1a\n\x16TOOL_PERMISSION_DENIED\x10\x04*y\n\rAttributeType\x12\x1e\n\x1a\x41TTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\n\n\x06STRING\x10\x01\x12\t\n\x05INT64\x10\x02\x12\n\n\x06\x44OUBLE\x10\x03\x12\x08\n\x04\x42OOL\x10\x04\x12\t\n\x05\x42YTES\x10\x05\x12\x10\n\x0cSTRING_ARRAY\x10\x06\x42\x99\x01\n2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\rEntitiesProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'routeiq.v1.telemetry.entities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2build.buf.gen.ssforge.routeiq.routeiq.v1.telemetryB\rEntitiesProtoZTbuf.build/gen/go/ssforge/routeiq/protocolbuffers/go/routeiq/v1/telemetry;telemetryv1'
  _globals['_COMPLETIONSTATUS']._serialized_start=61
  _globals['_COMPLETIONSTATUS']._serialized_end=181
  _globals['_FAILURECATEGORY']._serialized_start=184
  _globals['_FAILURECATEGORY']._serialized_end=394
  _globals['_AUTONOMYMODE']._serialized_start=396
  _globals['_AUTONOMYMODE']._serialized_end=494
  _globals['_RISKTIER']._serialized_start=496
  _globals['_RISKTIER']._serialized_end=578
  _globals['_PERMISSIONLEVEL']._serialized_start=580
  _globals['_PERMISSIONLEVEL']._serialized_end=690
  _globals['_TOOLRESULTSTATUS']._serialized_start=693
  _globals['_TOOLRESULTSTATUS']._serialized_end=829
  _globals['_ATTRIBUTETYPE']._serialized_start=831
  _globals['_ATTRIBUTETYPE']._serialized_end=952
# @@protoc_insertion_point(module_scope)
